version: "3.8"
# commands url http://host.docker.internal:6777
services:
  wds-ui-docs-traefik-app:
    image: "ghassanaldarwish/wds-ui-docs"
    restart: on-failure
    networks:
      - app-workspace-network
      - frontend
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wds-ui-docs-traefik-app.rule=Host(`wds-ui.webdrei.com`)"
      - "traefik.http.routers.wds-ui-docs-traefik-app.entrypoints=websecure"
      - "traefik.http.routers.wds-ui-docs-traefik-app.tls.certresolver=letsencrypt"
      - traefik.http.routers.wds-ui-docs-traefik-app.tls=true
      - "traefik.http.services.wds-ui-docs-traefik-app.loadbalancer.server.port=80"
    # env_file:
    #   - ../environment/wds-workspace/.env.local

networks:
  app-workspace-network:
    name: app-workspace-network

  frontend:
    name: frontend
