version: "3.8"
services:
  wds-ui-docs:
    image: "ghassanaldarwish/wds-ui-docs"
    restart: on-failure
    networks:
      - app-workspace-network
      - frontend
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wds-ui-docs.rule=Host(`wds-ui.webdrei.com`)"
      - "traefik.http.routers.wds-ui-docs.entrypoints=websecure"
      - "traefik.http.routers.wds-ui-docs.tls.certresolver=letsencrypt"
      - traefik.http.routers.wds-ui-docs.tls=true
      - "traefik.http.services.wds-ui-docs.loadbalancer.server.port=80"
    # env_file:
    #   - ./.env.local

networks:
  app-workspace-network:
    name: app-workspace-network

  frontend:
    name: frontend
