version: "3.8"
services:
  wds-ui-docs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    networks:
      - app-workspace-network
      - frontend
    environment:
      - IS_DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
      - ./src:/app/src

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wds-ui-docs.rule=Host(`wds-ui.localhost`)"
      - "traefik.http.services.wds-ui-docs.loadbalancer.server.port=3000"
    # env_file:
    #   - ../../environment/.env.local
networks:
  app-workspace-network:
    name: app-workspace-network

  frontend:
    name: frontend
